credentials:
  usernames:
    user1:
      name: สมชาย
      password: '$2b$12$xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
    user2:
      name: สมหญิง
      password: '$2b$12$yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy'

cookie:
  name: nongchuai_cookie
  key: some_random_key
  expiry_days: 30
